backend:
  name: github
  repo: USERNAME/arcieri-sito
  branch: main
  base_url: https://effulgent-banoffee-eea359.netlify.app
  auth_endpoint: /auth
media_folder: "media"
public_folder: "/media"
collections:
  - name: "pagine"
    label: "Pagine"
    files:
      - file: "content/home.md"
        name: "home"
        label: "Homepage"
        fields:
          - { label: "Contenuto", name: "body", widget: "markdown" }
      - file: "content/chi-siamo.md"
        name: "chi_siamo"
        label: "Chi siamo"
        fields:
          - { label: "Contenuto", name: "body", widget: "markdown" }
      - file: "content/attivita.md"
        name: "attivita"
        label: "Attività"
        fields:
          - { label: "Contenuto", name: "body", widget: "markdown" }
      - file: "content/galleria.md"
        name: "galleria"
        label: "Galleria"
        fields:
          - { label: "Contenuto", name: "body", widget: "markdown" }